ateam: bin/watcher --config ./configs/ateam.json
chainylira: bin/watcher --config ./configs/chainylira.json
dokia: bin/watcher --config ./configs/dokia.json
dos-ibc: bin/watcher --config ./configs/dos-ibc.json
hashquarkchain: bin/watcher --config ./configs/hashquarkchain.json
ibc-band-testnet1: bin/watcher --config ./configs/ibc-band-testnet1.json
iqlusionchain: bin/watcher --config ./configs/iqlusionchain.json
irishub: bin/watcher --config ./configs/irishub.json
kappa: bin/watcher --config ./configs/kappa.json
kava-ibc: bin/watcher --config ./configs/kava-ibc.json
mallowchain: bin/watcher --config ./configs/mallowchain.json
melea-11: bin/watcher --config ./configs/melea-11.json
morpheus-ibc-3000: bin/watcher --config ./configs/morpheus-ibc-3000.json
newroadchain: bin/watcher --config ./configs/newroadchain.json
nochainnogain: bin/watcher --config ./configs/nochainnogain.json
okchain: bin/watcher --config ./configs/okchain.json
ping-ibc: bin/watcher --config ./configs/ping-ibc.json
ptpchain: bin/watcher --config ./configs/ptpchain.json
pylonchain: bin/watcher --config ./configs/pylonchain.json
simplystaking: bin/watcher --config ./configs/simplystaking.json
stakingfund: bin/watcher --config ./configs/stakingfund.json
umbrellachain: bin/watcher --config ./configs/umbrellachain.json
vitwitchain-1: bin/watcher --config ./configs/vitwitchain-1.json
vitwitchain: bin/watcher --config ./configs/vitwitchain.json
westaking: bin/watcher --config ./configs/westaking.json
all: bin/watchers --configs configs/
