dokia: bin/watcher --config ./configs/dokia.json
ibc-band-testnet1: bin/watcher --config ./configs/ibc-band-testnet1.json
irishub: bin/watcher --config ./configs/irishub.json
kappa: bin/watcher --config ./configs/kappa.json
kava-ibc: bin/watcher --config ./configs/kava-ibc.json
melea-11: bin/watcher --config ./configs/melea-11.json
morpheus-ibc-3000: bin/watcher --config ./configs/morpheus-ibc-3000.json
ping-ibc: bin/watcher --config ./configs/ping-ibc.json
ptpchain: bin/watcher --config ./configs/ptpchain.json
pylonchain: bin/watcher --config ./configs/pylonchain.json
umbrellachain: bin/watcher --config ./configs/umbrellachain.json
vitwitchain-1: bin/watcher --config ./configs/vitwitchain-1.json
vitwitchain: bin/watcher --config ./configs/vitwitchain.json
all: bin/watchers --configs configs/
