worker: bin/cmd --config ./configs/dokia.json
worker: bin/cmd --config ./configs/ibc-band-testnet1.json
worker: bin/cmd --config ./configs/irishub.json
worker: bin/cmd --config ./configs/kappa.json
worker: bin/cmd --config ./configs/kava-ibc.json
worker: bin/cmd --config ./configs/melea-11.json
worker: bin/cmd --config ./configs/morpheus-ibc-3000.json
worker: bin/cmd --config ./configs/ping-ibc.json
worker: bin/cmd --config ./configs/ptpchain.json
worker: bin/cmd --config ./configs/pylonchain.json
worker: bin/cmd --config ./configs/umbrellachain.json
worker: bin/cmd --config ./configs/vitwitchain-1.json
worker: bin/cmd --config ./configs/vitwitchain.json
