#!/bin/bash
watcher --tmRPC "ws://gozmelea.mycryptobets.com:26657/websocket" --rabbitMQ "$RABBITMQ" --zone gozmelea.mycryptobets.com &
watcher --tmRPC "ws://ibc.westaking.io:26657/websocket" --rabbitMQ "$RABBITMQ" --zone ibc.westaking.io &
watcher --tmRPC "ws://goz.irisnet.org:26657/websocket" --rabbitMQ "$RABBITMQ" --zone goz.irisnet.org &
watcher --tmRPC "ws://achain.nodeateam.com:26657/websocket" --rabbitMQ "$RABBITMQ" --zone achain.nodeateam.com &
watcher --tmRPC "ws://n01.gozlira.com:26657/websocket" --rabbitMQ "$RABBITMQ" --zone n01.gozlira.com &
watcher --tmRPC "ws://ibc01.dokia.cloud:26657/websocket" --rabbitMQ "$RABBITMQ" --zone ibc01.dokia.cloud &
watcher --tmRPC "ws://goz.dos.network:26657/websocket" --rabbitMQ "$RABBITMQ" --zone goz.dos.network &
watcher --tmRPC "ws://152.32.135.74:26657/websocket" --rabbitMQ "$RABBITMQ" --zone 152.32.135.74 &
watcher --tmRPC "ws://fridayco.in:26657/websocket" --rabbitMQ "$RABBITMQ" --zone fridayco.in &
watcher --tmRPC "ws://95.217.135.90:26657/websocket" --rabbitMQ "$RABBITMQ" --zone 95.217.135.90 &
watcher --tmRPC "ws://ibc-testnet1.bandchain.org:26657/websocket" --rabbitMQ "$RABBITMQ" --zone ibc-testnet1.bandchain.org &
watcher --tmRPC "ws://157.230.255.202:26657/websocket" --rabbitMQ "$RABBITMQ" --zone 157.230.255.202 &
watcher --tmRPC "ws://ibc-alpha.kava.io:26657/websocket" --rabbitMQ "$RABBITMQ" --zone ibc-alpha.kava.io &
watcher --tmRPC "ws://ibc-alpha.desmos.network:26657/websocket" --rabbitMQ "$RABBITMQ" --zone ibc-alpha.desmos.network &
watcher --tmRPC "ws://ibc.ping.pub:26657/websocket" --rabbitMQ "$RABBITMQ" --zone ibc.ping.pub &
watcher --tmRPC "ws://3.211.57.24:26657/websocket" --rabbitMQ "$RABBITMQ" --zone 3.211.57.24 &
watcher --tmRPC "ws://ibc.staking.fund:26657/websocket" --rabbitMQ "$RABBITMQ" --zone ibc.staking.fund &
watcher --tmRPC "ws://ibct01.newroad.network:26657/websocket" --rabbitMQ "$RABBITMQ" --zone ibct01.newroad.network &
watcher --tmRPC "ws://13.231.12.191:26657/websocket" --rabbitMQ "$RABBITMQ" --zone 13.231.12.191 &
watcher --tmRPC "ws://95.217.135.90:26657/websocket" --rabbitMQ "$RABBITMQ" --zone 95.217.135.90 &
watcher --tmRPC "ws://ibc.blockscape.network:26657/websocket" --rabbitMQ "$RABBITMQ" --zone ibc.blockscape.network &
watcher --tmRPC "ws://shitcoincasinos.com:26657/websocket" --rabbitMQ "$RABBITMQ" --zone shitcoincasinos.com &
watcher --tmRPC "ws://ibc.umbrellavalidator.com:26657/websocket" --rabbitMQ "$RABBITMQ" --zone ibc.umbrellavalidator.com &
watcher --tmRPC "ws://ibc1.vitwit.in:26657/websocket" --rabbitMQ "$RABBITMQ" --zone ibc1.vitwit.in &
watcher --tmRPC "ws://ibc.vitwit.in:26657/websocket" --rabbitMQ "$RABBITMQ" --zone ibc.vitwit.in &
watcher --tmRPC "ws://80.64.211.64:26657/websocket" --rabbitMQ "$RABBITMQ" --zone 80.64.211.64 &
watcher --tmRPC "ws://goz.val.network:26657/websocket" --rabbitMQ "$RABBITMQ" --zone goz.val.network &
watcher --tmRPC "ws://testnet.dawns.world:26657/websocket" --rabbitMQ "$RABBITMQ" --zone testnet.dawns.world &
watcher --tmRPC "ws://goz.konstellation.tech:26657/websocket" --rabbitMQ "$RABBITMQ" --zone goz.konstellation.tech &
watcher --tmRPC "ws://167.179.104.210:26657/websocket" --rabbitMQ "$RABBITMQ" --zone 167.179.104.210 &
watcher --tmRPC "ws://setan.ml:26657/websocket" --rabbitMQ "$RABBITMQ" --zone setan.ml &
watcher --tmRPC "ws://goz.01node.com:26657/websocket" --rabbitMQ "$RABBITMQ" --zone goz.01node.com &
watcher --tmRPC "ws://capychain.com:26657/websocket" --rabbitMQ "$RABBITMQ" --zone capychain.com &
watcher --tmRPC "ws://51.178.119.163:26657/websocket" --rabbitMQ "$RABBITMQ" --zone 51.178.119.163 &
watcher --tmRPC "ws://dropschain.com:26657/websocket" --rabbitMQ "$RABBITMQ" --zone dropschain.com &
watcher --tmRPC "ws://goz.everstake.one:26657/websocket" --rabbitMQ "$RABBITMQ" --zone goz.everstake.one &
watcher --tmRPC "ws://51.178.119.162:26657/websocket" --rabbitMQ "$RABBITMQ" --zone 51.178.119.162 &
watcher --tmRPC "ws://goz.jptpool.com:26657/websocket" --rabbitMQ "$RABBITMQ" --zone goz.jptpool.com &
watcher --tmRPC "ws://goz.gunray.xyz:26657/websocket" --rabbitMQ "$RABBITMQ" --zone goz.gunray.xyz &
watcher --tmRPC "ws://49.12.106.6:26657/websocket" --rabbitMQ "$RABBITMQ" --zone 49.12.106.6 &
watcher --tmRPC "ws://tnet-csg.c9ret.xyz:26657/websocket" --rabbitMQ "$RABBITMQ" --zone tnet-csg.c9ret.xyz &
watcher --tmRPC "ws://supernova.commonwealth.im:26657/websocket" --rabbitMQ "$RABBITMQ" --zone supernova.commonwealth.im &
watcher --tmRPC "ws://173.249.12.108:26657/websocket" --rabbitMQ "$RABBITMQ" --zone 173.249.12.108 &
watcher --tmRPC "ws://chain.exchange-fees.com:26657/websocket" --rabbitMQ "$RABBITMQ" --zone chain.exchange-fees.com &
watcher --tmRPC "ws://ibc.izo.ro:26657/websocket" --rabbitMQ "$RABBITMQ" --zone ibc.izo.ro &
watcher --tmRPC "ws://goz.kalpatech.co:26657/websocket" --rabbitMQ "$RABBITMQ" --zone goz.kalpatech.co &
watcher --tmRPC "ws://goz.01node.com:26657/websocket" --rabbitMQ "$RABBITMQ" --zone goz.01node.com &
watcher --tmRPC "ws://ibc.cosmoon.org:26657/websocket" --rabbitMQ "$RABBITMQ" --zone ibc.cosmoon.org &
watcher --tmRPC "ws://mmmh.sytes.net:26657/websocket" --rabbitMQ "$RABBITMQ" --zone mmmh.sytes.net &
wait