#!/bin/bash
watcher --tmRPC "ws://goz.01node.com:26657/websocket" --rabbitMQ "$RABBITMQ" --zone 01node &
watcher --tmRPC "ws://achain.nodeateam.com:26657/websocket" --rabbitMQ "$RABBITMQ" --zone ateam &
watcher --tmRPC "ws://capychain.com:26657/websocket" --rabbitMQ "$RABBITMQ" --zone capychain &
watcher --tmRPC "ws://n01.gozlira.com:26657/websocket" --rabbitMQ "$RABBITMQ" --zone chainylira &
watcher --tmRPC "ws://51.178.119.163:26657/websocket" --rabbitMQ "$RABBITMQ" --zone coco-post-chain &
watcher --tmRPC "ws://goz.val.network:26657/websocket" --rabbitMQ "$RABBITMQ" --zone Compass &
watcher --tmRPC "ws://testnet.dawns.world:26657/websocket" --rabbitMQ "$RABBITMQ" --zone dawnsworld &
watcher --tmRPC "ws://ibc01.dokia.cloud:26657/websocket" --rabbitMQ "$RABBITMQ" --zone dokia &
watcher --tmRPC "ws://goz.dos.network:26657/websocket" --rabbitMQ "$RABBITMQ" --zone dos-ibc &
watcher --tmRPC "ws://dropschain.com:26657/websocket" --rabbitMQ "$RABBITMQ" --zone dropschain &
watcher --tmRPC "ws://goz.everstake.one:26657/websocket" --rabbitMQ "$RABBITMQ" --zone everstakechain &
watcher --tmRPC "ws://51.178.119.162:26657/websocket" --rabbitMQ "$RABBITMQ" --zone freeflix-media-hub &
watcher --tmRPC "ws://goz.jptpool.com:26657/websocket" --rabbitMQ "$RABBITMQ" --zone gemstone &
watcher --tmRPC "ws://goz.gunray.xyz:26657/websocket" --rabbitMQ "$RABBITMQ" --zone gunchain &
watcher --tmRPC "ws://152.32.135.74:26657/websocket" --rabbitMQ "$RABBITMQ" --zone hashquarkchain &
watcher --tmRPC "ws://ibc-testnet1.bandchain.org:26657/websocket" --rabbitMQ "$RABBITMQ" --zone ibc-band-testnet1 &
watcher --tmRPC "ws://fridayco.in:26657/websocket" --rabbitMQ "$RABBITMQ" --zone iqlusionchain &
watcher --tmRPC "ws://goz.irisnet.org:26657/websocket" --rabbitMQ "$RABBITMQ" --zone irishub &
watcher --tmRPC "ws://49.12.106.6:26657/websocket" --rabbitMQ "$RABBITMQ" --zone isillienchain &
watcher --tmRPC "ws://157.230.255.202:26657/websocket" --rabbitMQ "$RABBITMQ" --zone kappa &
watcher --tmRPC "ws://ibc-alpha.kava.io:26657/websocket" --rabbitMQ "$RABBITMQ" --zone kava-ibc &
watcher --tmRPC "ws://goz.konstellation.tech:26657/websocket" --rabbitMQ "$RABBITMQ" --zone konstellation &
watcher --tmRPC "ws://3.211.57.24:26657/websocket" --rabbitMQ "$RABBITMQ" --zone mallowchain &
watcher --tmRPC "ws://gozmelea.mycryptobets.com:26657/websocket" --rabbitMQ "$RABBITMQ" --zone melea-11 &
watcher --tmRPC "ws://ibc-alpha.desmos.network:26657/websocket" --rabbitMQ "$RABBITMQ" --zone morpheus-ibc-3000 &
watcher --tmRPC "ws://ibct01.newroad.network:26657/websocket" --rabbitMQ "$RABBITMQ" --zone newroadchain &
watcher --tmRPC "ws://167.179.104.210:26657/websocket" --rabbitMQ "$RABBITMQ" --zone nibiru-ibc &
watcher --tmRPC "ws://ibc.blockscape.network:26657/websocket" --rabbitMQ "$RABBITMQ" --zone nochainnogain &
watcher --tmRPC "ws://13.231.12.191:26657/websocket" --rabbitMQ "$RABBITMQ" --zone okchain &
watcher --tmRPC "ws://ibc.ping.pub:26657/websocket" --rabbitMQ "$RABBITMQ" --zone ping-ibc &
watcher --tmRPC "ws://95.217.135.90:26657/websocket" --rabbitMQ "$RABBITMQ" --zone ptpchain &
watcher --tmRPC "ws://shitcoincasinos.com:26657/websocket" --rabbitMQ "$RABBITMQ" --zone pylonchain &
watcher --tmRPC "ws://tnet-csg.c9ret.xyz:26657/websocket" --rabbitMQ "$RABBITMQ" --zone retz80chain &
watcher --tmRPC "ws://setan.ml:26657/websocket" --rabbitMQ "$RABBITMQ" --zone setanchain &
watcher --tmRPC "ws://80.64.211.64:26657/websocket" --rabbitMQ "$RABBITMQ" --zone simplystaking &
watcher --tmRPC "ws://34.87.102.225:26657/websocket" --rabbitMQ "$RABBITMQ" --zone stakematic-asia &
watcher --tmRPC "ws://ibc.staking.fund:26657/websocket" --rabbitMQ "$RABBITMQ" --zone stakingfund &
watcher --tmRPC "ws://supernova.commonwealth.im:26657/websocket" --rabbitMQ "$RABBITMQ" --zone supernova &
watcher --tmRPC "ws://ibc.umbrellavalidator.com:26657/websocket" --rabbitMQ "$RABBITMQ" --zone umbrellachain &
watcher --tmRPC "ws://173.249.12.108:26657/websocket" --rabbitMQ "$RABBITMQ" --zone vipnamai &
watcher --tmRPC "ws://ibc1.vitwit.in:26657/websocket" --rabbitMQ "$RABBITMQ" --zone vitwitchain-1 &
watcher --tmRPC "ws://ibc.vitwit.in:26657/websocket" --rabbitMQ "$RABBITMQ" --zone vitwitchain &
watcher --tmRPC "ws://chain.exchange-fees.com:26657/websocket" --rabbitMQ "$RABBITMQ" --zone vostok-1 &
watcher --tmRPC "ws://ibc.westaking.io:26657/websocket" --rabbitMQ "$RABBITMQ" --zone westaking &
wait
